/**
 * Games ride the machinery the chat already has.
 *
 * A room holds at most one active game, stored as a single Redis hash beside
 * the roster. Every accepted move rewrites that hash and pushes the whole game
 * down the existing SSE stream, so clients need no second connection, no
 * polling and no reconciliation — the same fan-out that delivers messages
 * delivers board state.
 *
 * Every engine is a pure function of (game, seat, move). No clocks, no
 * randomness read from the ambient environment, no Redis: dice come in as part
 * of the move payload, generated by the route. That is what makes the rules
 * unit-testable without a server, and it is where the real complexity of chess
 * and ludo is allowed to live.
 */

export type GameKind = 'tictactoe' | 'connect4' | 'chess' | 'ludo' | 'race';

export type GameStatus = 'waiting' | 'active' | 'over';

export interface GamePlayer {
  uid: string;
  name: string;
  color: string;
  /** Index into `players`; also the mark/side the engine uses. */
  seat: number;
}

/* ----------------------------------------------------------------- boards */

/** Null means empty; a number is the seat index that owns the cell. */
export type Cells = (number | null)[];

export interface TicTacToeBoard {
  kind: 'tictactoe';
  cells: Cells; // 9, row-major
}

export interface Connect4Board {
  kind: 'connect4';
  cells: Cells; // 42, row-major, row 0 is the top
}

/** 'wK' | 'bp' style: colour letter + piece letter, uppercase = white. */
export type ChessPiece = string;

export interface ChessBoard {
  kind: 'chess';
  /** 64 squares, index 0 = a8, index 63 = h1 (rank 8 first, as printed). */
  squares: (ChessPiece | null)[];
  /** Castling rights still available, e.g. "KQkq" or "-". */
  castling: string;
  /** En-passant target square index, or null. */
  enPassant: number | null;
  /** Half-moves since the last capture or pawn move (fifty-move rule). */
  halfmove: number;
  /** Set when the side to move is in check — drives the UI warning. */
  check: boolean;
  /** Squares of the last move, for highlighting. */
  lastMove: [number, number] | null;
}

/**
 * Ludo token progress.
 *
 * -1  = still in the yard, needs a 6 to enter
 * 0-50 = squares travelled along the shared 52-square track
 * 51-56 = the player's private home column
 * 57  = home
 *
 * Storing *progress travelled* rather than an absolute square is what keeps
 * the four players' paths comparable: the absolute square is derived from
 * progress plus that seat's entry offset, so capture checks stay simple.
 */
export interface LudoBoard {
  kind: 'ludo';
  /** tokens[seat][tokenIndex] = progress. Always 4 tokens per seat. */
  tokens: number[][];
  /** Current dice face, or null when the seat still has to roll. */
  dice: number | null;
  /** Consecutive sixes this turn; three in a row forfeits the turn. */
  sixes: number;
}

export interface RaceCar {
  /** Cells travelled along the track. */
  pos: number;
  /** Set when the driver span out and loses their next turn. */
  stalled: boolean;
}

export interface RaceBoard {
  kind: 'race';
  cars: RaceCar[];
  length: number;
  /** Last roll per seat, purely for display. */
  lastRoll: (number | null)[];
}

export type Board =
  | TicTacToeBoard
  | Connect4Board
  | ChessBoard
  | LudoBoard
  | RaceBoard;

/* ------------------------------------------------------------------ game */

export interface Game {
  id: string;
  kind: GameKind;
  players: GamePlayer[];
  /** Seats required before play starts. */
  seats: number;
  /** Seat index whose turn it is. */
  turn: number;
  status: GameStatus;
  /** Seat index of the winner, or null for a draw once status is 'over'. */
  winner: number | null;
  board: Board;
  createdAt: number;
  updatedAt: number;
  /**
   * Bumped on every accepted move. The client echoes the version it acted on,
   * so a double-click or a retried request cannot apply the same move twice.
   */
  version: number;
  /** Short human-readable description of the last thing that happened. */
  note: string;
  /** uid of whoever opened the table. */
  openedBy: string;
}

/** A move is validated by the engine, never trusted from the client. */
export type Move = Record<string, unknown>;

export type ApplyResult =
  | { ok: true; game: Game }
  | { ok: false; error: string };

export interface GameEngine {
  kind: GameKind;
  label: string;
  blurb: string;
  minSeats: number;
  maxSeats: number;
  /** Emoji shown on the lobby button. */
  icon: string;
  createBoard(seats: number): Board;
  /**
   * Validate and apply one move. Must be pure and must never mutate `game`.
   * Returning an error is normal control flow, not an exception.
   */
  apply(game: Game, seat: number, move: Move): ApplyResult;
}

/** Convenience for engines: a shallow-cloned game with common fields set. */
export function advance(
  game: Game,
  patch: Partial<Game> & { board: Board }
): Game {
  return { ...game, ...patch, updatedAt: game.updatedAt };
}

/** Reads a bounded integer out of an untrusted move payload. */
export function intField(
  move: Move,
  name: string,
  min: number,
  max: number
): number | null {
  const raw = move[name];
  if (typeof raw !== 'number' || !Number.isInteger(raw)) return null;
  if (raw < min || raw > max) return null;
  return raw;
}
